### ISSUE TITLE
Add missing commands and events for remoteDisengage and findComponent

### ISSUE THREAD

**Issue by berka3** [open200/xesar-connect#19]

**Comment by MartinPfeffer** [comment]
Commands (and Events) to add
- remoteDisengage
- findComponent

Workflow
- subscriptions to the response topics are to handle from the developer
- subscription to the "/userId/err" is handled during login
- `sendCommand(Command, Event::class): deferred<T> `
- error (needs investigation):
  - throws XesarApiException (event as parameter) 
  - return pair deferred<T,err>
- look into using reified for deferred command parameter
